const countries = [
	{ nome: "Afeganistão", cor: "#000000" },
	{ nome: "África do Sul", cor: "#008000" },
	{ nome: "Albânia", cor: "#FF0000" },
	{ nome: "Alemanha", cor: "#000000" },
	{ nome: "Andorra", cor: "#0000FF" },
	{ nome: "Angola", cor: "#FF0000" },
	{ nome: "Antígua e Barbuda", cor: "#FF0000" },
	{ nome: "Arábia Saudita", cor: "#008000" },
	{ nome: "Argélia", cor: "#008000" },
	{ nome: "Argentina", cor: "#87CEEB" },
	{ nome: "Armênia", cor: "#FF0000" },
	{ nome: "Austrália", cor: "#0000FF" },
	{ nome: "Áustria", cor: "#FF0000" },
	{ nome: "Azerbaijão", cor: "#0000FF" },
	{ nome: "Bahamas", cor: "#87CEEB" },
	{ nome: "Bangladesh", cor: "#008000" },
	{ nome: "Barbados", cor: "#0000FF" },
	{ nome: "Barein", cor: "#FF0000" },
	{ nome: "Belarus", cor: "#FF0000" },
	{ nome: "Bélgica", cor: "#FF0000" },
	{ nome: "Belize", cor: "#0000FF" },
	{ nome: "Benin", cor: "#008000" },
	{ nome: "Bolívia (Estado Plurinacional da)", cor: "#FF0000" },
	{ nome: "Bósnia e Herzegovina", cor: "#0000FF" },
	{ nome: "Botsuana", cor: "#87CEEB" },
	{ nome: "Brasil", cor: "#008000" },
	{ nome: "Brunei", cor: "#FFFF00" },
	{ nome: "Bulgária", cor: "#FFFFFF" },
	{ nome: "Burkina Faso", cor: "#FF0000" },
	{ nome: "Burundi", cor: "#FF0000" },
	{ nome: "Butão", cor: "#FFFF00" },
	{ nome: "Cabo Verde", cor: "#0000FF" },
	{ nome: "Camarões", cor: "#008000" },
	{ nome: "Camboja", cor: "#FF0000" },
	{ nome: "Canadá", cor: "#FF0000" },
	{ nome: "Catar", cor: "#800000" },
	{ nome: "Cazaquistão", cor: "#87CEEB" },
	{ nome: "Chade", cor: "#0000FF" },
	{ nome: "Chile", cor: "#FF0000" },
	{ nome: "China", cor: "#FF0000" },
	{ nome: "Chipre", cor: "#FFFFFF" },
	{ nome: "Colômbia", cor: "#FFFF00" },
	{ nome: "Comores", cor: "#008000" },
	{ nome: "Congo", cor: "#008000" },
	{ nome: "Costa do Marfim", cor: "#FFA500" },
	{ nome: "Costa Rica", cor: "#FF0000" },
	{ nome: "Croácia", cor: "#FF0000" },
	{ nome: "Cuba", cor: "#0000FF" },
	{ nome: "Dinamarca", cor: "#FF0000" },
	{ nome: "Djibouti", cor: "#87CEEB" },
	{ nome: "Dominica", cor: "#008000" },
	{ nome: "Egito", cor: "#FF0000" },
	{ nome: "El Salvador", cor: "#0000FF" },
	{ nome: "Emirados Árabes Unidos", cor: "#008000" },
	{ nome: "Equador", cor: "#FFFF00" },
	{ nome: "Eritreia", cor: "#008000" },
	{ nome: "Eslováquia", cor: "#0000FF" },
	{ nome: "Eslovênia", cor: "#0000FF" },
	{ nome: "Espanha", cor: "#FF0000" },
	{ nome: "Estados Unidos da América", cor: "#0000FF" },
	{ nome: "Estônia", cor: "#0000FF" },
	{ nome: "Eswatini", cor: "#0000FF" },
	{ nome: "Etiópia", cor: "#008000" },
	{ nome: "Federação da Rússia", cor: "#FF0000" },
	{ nome: "Fiji", cor: "#87CEEB" },
	{ nome: "Filipinas", cor: "#0000FF" },
	{ nome: "Finlândia", cor: "#FFFFFF" },
	{ nome: "França", cor: "#0000FF" },
	{ nome: "Gabão", cor: "#008000" },
	{ nome: "Gâmbia", cor: "#FF0000" },
	{ nome: "Gana", cor: "#FF0000" },
	{ nome: "Geórgia", cor: "#FFFFFF" },
	{ nome: "Granada", cor: "#FF0000" },
	{ nome: "Grécia", cor: "#0000FF" },
	{ nome: "Guatemala", cor: "#87CEEB" },
	{ nome: "Guiana", cor: "#008000" },
	{ nome: "Guiné", cor: "#FF0000" },
	{ nome: "Guiné-Bissau", cor: "#FF0000" },
	{ nome: "Guiné Equatorial", cor: "#008000" },
	{ nome: "Haiti", cor: "#0000FF" },
	{ nome: "Holanda", cor: "#FFA500" },
	{ nome: "Honduras", cor: "#87CEEB" },
	{ nome: "Hungria", cor: "#FF0000" },
	{ nome: "Iêmen", cor: "#FF0000" },
	{ nome: "Ilhas Marshall", cor: "#0000FF" },
	{ nome: "Ilhas Salomão", cor: "#0000FF" },
	{ nome: "Índia", cor: "#FFA500" },
	{ nome: "Indonésia", cor: "#FF0000" },
	{ nome: "Irã (República Islâmica do)", cor: "#008000" },
	{ nome: "Iraque", cor: "#FF0000" },
	{ nome: "Irlanda", cor: "#008000" },
	{ nome: "Islândia", cor: "#0000FF" },
	{ nome: "Israel", cor: "#0000FF" },
	{ nome: "Itália", cor: "#008000" },
	{ nome: "Jamaica", cor: "#FFFF00" },
	{ nome: "Japão", cor: "#FF0000" },
	{ nome: "Jordânia", cor: "#000000" },
	{ nome: "Kiribati", cor: "#FF0000" },
	{ nome: "Kuwait", cor: "#008000" },
	{ nome: "Lesoto", cor: "#0000FF" },
	{ nome: "Letônia", cor: "#800000" },
	{ nome: "Líbano", cor: "#FF0000" },
	{ nome: "Libéria", cor: "#FF0000" },
	{ nome: "Líbia", cor: "#FF0000" },
	{ nome: "Liechtenstein", cor: "#0000FF" },
	{ nome: "Lituânia", cor: "#FFFF00" },
	{ nome: "Luxemburgo", cor: "#87CEEB" },
	{ nome: "Macedônia do Norte", cor: "#FF0000" },
	{ nome: "Madagascar", cor: "#FF0000" },
	{ nome: "Malásia", cor: "#FFFF00" },
	{ nome: "Malauí", cor: "#000000" },
	{ nome: "Maldivas", cor: "#FF0000" },
	{ nome: "Mali", cor: "#008000" },
	{ nome: "Malta", cor: "#FF0000" },
	{ nome: "Marrocos", cor: "#FF0000" },
	{ nome: "Maurício", cor: "#FF0000" },
	{ nome: "Mauritânia", cor: "#008000" },
	{ nome: "México", cor: "#008000" },
	{ nome: "Mianmar", cor: "#FFFF00" },
	{ nome: "Micronésia (Estados Federados da)", cor: "#87CEEB" },
	{ nome: "Moçambique", cor: "#FF0000" },
	{ nome: "Moldávia (República da)", cor: "#0000FF" },
	{ nome: "Mônaco", cor: "#FF0000" },
	{ nome: "Mongólia", cor: "#FF0000" },
	{ nome: "Montenegro", cor: "#FF0000" },
	{ nome: "Namíbia", cor: "#0000FF" },
	{ nome: "Nauru", cor: "#0000FF" },
	{ nome: "Nepal", cor: "#FF0000" },
	{ nome: "Nicarágua", cor: "#87CEEB" },
	{ nome: "Niger", cor: "#FFA500" },
	{ nome: "Nigéria", cor: "#008000" },
	{ nome: "Noruega", cor: "#FF0000" },
	{ nome: "Nova Zelândia", cor: "#000000" },
	{ nome: "Omã", cor: "#FF0000" },
	{ nome: "Palau", cor: "#87CEEB" },
	{ nome: "Palestina", cor: "#000000" },
	{ nome: "Panamá", cor: "#FF0000" },
	{ nome: "Papua Nova Guiné", cor: "#FF0000" },
	{ nome: "Paquistão", cor: "#008000" },
	{ nome: "Paraguai", cor: "#FF0000" },
	{ nome: "Peru", cor: "#FF0000" },
	{ nome: "Polônia", cor: "#FF0000" },
	{ nome: "Portugal", cor: "#008000" },
	{ nome: "Quênia", cor: "#000000" },
	{ nome: "Quirguistão", cor: "#FF0000" },
	{ nome: "Reino Unido da Grã-Bretanha e Irlanda do Norte", cor: "#0000FF" },
	{ nome: "República Centro-Africana", cor: "#0000FF" },
	{ nome: "República da Coreia", cor: "#FFFFFF" },
	{ nome: "República Democrática do Congo", cor: "#0000FF" },
	{ nome: "República Democrática Popular do Laos", cor: "#0000FF" },
	{ nome: "República Dominicana", cor: "#0000FF" },
	{ nome: "República Popular Democrática da Coreia", cor: "#FF0000" },
	{ nome: "República Tcheca", cor: "#FF0000" },
	{ nome: "Romênia", cor: "#FFFF00" },
	{ nome: "Ruanda", cor: "#87CEEB" },
	{ nome: "Samoa", cor: "#FF0000" },
	{ nome: "San Marino", cor: "#87CEEB" },
	{ nome: "Santa Lúcia", cor: "#87CEEB" },
	{ nome: "São Cristóvão e Nevis", cor: "#008000" },
	{ nome: "São Tomé e Príncipe", cor: "#008000" },
	{ nome: "São Vicente e Granadinas", cor: "#0000FF" },
	{ nome: "Seichelles", cor: "#0000FF" },
	{ nome: "Senegal", cor: "#008000" },
	{ nome: "Serra Leoa", cor: "#008000" },
	{ nome: "Sérvia", cor: "#FF0000" },
	{ nome: "Singapura", cor: "#FF0000" },
	{ nome: "Síria", cor: "#FF0000" },
	{ nome: "Somália", cor: "#87CEEB" },
	{ nome: "Sri Lanka", cor: "#800000" },
	{ nome: "Sudão", cor: "#FF0000" },
	{ nome: "Sudão do Sul", cor: "#000000" },
	{ nome: "Suécia", cor: "#FFFF00" },
	{ nome: "Suíça", cor: "#FF0000" },
	{ nome: "Suriname", cor: "#008000" },
	{ nome: "Tadjiquistão", cor: "#FF0000" },
	{ nome: "Tailândia", cor: "#0000FF" },
	{ nome: "Tanzânia, República Unida da", cor: "#008000" },
	{ nome: "Timor-Leste", cor: "#FF0000" },
	{ nome: "Togo", cor: "#008000" },
	{ nome: "Tonga", cor: "#FF0000" },
	{ nome: "Trinidad e Tobago", cor: "#FF0000" },
	{ nome: "Tunísia", cor: "#FF0000" },
	{ nome: "Turcomenistão", cor: "#008000" },
	{ nome: "Turquia", cor: "#FF0000" },
	{ nome: "Tuvalu", cor: "#87CEEB" },
	{ nome: "Ucrânia", cor: "#FFFF00" },
	{ nome: "Uganda", cor: "#000000" },
	{ nome: "Uruguai", cor: "#87CEEB" },
	{ nome: "Uzbequistão", cor: "#0000FF" },
	{ nome: "Vanuatu", cor: "#FF0000" },
	{ nome: "Venezuela (República Bolivariana da)", cor: "#FFFF00" },
	{ nome: "Vietnã", cor: "#FF0000" },
	{ nome: "Zâmbia", cor: "#008000" },
	{ nome: "Zimbábue", cor: "#008000" }
];