const countries = [
	"Afeganistão",
	"África do Sul",
	"Albânia",
	"Alemanha",
	"Andorra",
	"Angola",
	"Antígua e Barbuda",
	"Arábia Saudita",
	"Argélia",
	"Argentina",
	"Armênia",
	"Austrália",
	"Áustria",
	"Azerbaijão",
	"Bahamas",
	"Bangladesh",
	"Barbados",
	"Barein",
	"Belarus",
	"Bélgica",
	"Belize",
	"Benin",
	"Bolívia (Estado Plurinacional da)",
	"Bósnia e Herzegovina",
	"Botsuana",
	"Brasil",
	"Brunei",
	"Bulgária",
	"Burkina Faso",
	"Burundi",
	"Butão",
	"Cabo Verde",
	"Camarões",
	"Camboja",
	"Canadá",
	"Catar",
	"Cazaquistão",
	"Chade",
	"Chile",
	"China",
	"Chipre",
	"Colômbia",
	"Comores",
	"Congo",
	"Costa do Marfim",
	"Costa Rica",
	"Croácia",
	"Cuba",
	"Dinamarca",
	"Djibouti",
	"Dominica",
	"Egito",
	"El Salvador",
	"Emirados Árabes Unidos",
	"Equador",
	"Eritreia",
	"Eslováquia",
	"Eslovênia",
	"Espanha",
	"Estados Unidos da América",
	"Estônia",
	"Eswatini",
	"Etiópia",
	"Federação da Rússia",
	"Fiji",
	"Filipinas",
	"Finlândia",
	"França",
	"Gabão",
	"Gâmbia",
	"Gana",
	"Geórgia",
	"Granada",
	"Grécia",
	"Guatemala",
	"Guiana",
	"Guiné",
	"Guiné-Bissau",
	"Guiné Equatorial",
	"Haiti",
	"Holanda",
	"Honduras",
	"Hungria",
	"Iêmen",
	"Ilhas Marshall",
	"Ilhas Salomão",
	"Índia",
	"Indonésia",
	"Irã (República Islâmica do)",
	"Iraque",
	"Irlanda",
	"Islândia",
	"Israel",
	"Itália",
	"Jamaica",
	"Japão",
	"Jordânia",
	"Kiribati",
	"Kuwait",
	"Lesoto",
	"Letônia",
	"Líbano",
	"Libéria",
	"Líbia",
	"Liechtenstein",
	"Lituânia",
	"Luxemburgo",
	"Macedônia do Norte",
	"Madagascar",
	"Malásia",
	"Malauí",
	"Maldivas",
	"Mali",
	"Malta",
	"Marrocos",
	"Maurício",
	"Mauritânia",
	"México",
	"Mianmar",
	"Micronésia (Estados Federados da)",
	"Moçambique",
	"Moldávia (República da)",
	"Mônaco",
	"Mongólia",
	"Montenegro",
	"Namíbia",
	"Nauru",
	"Nepal",
	"Nicarágua",
	"Niger",
	"Nigéria",
	"Noruega",
	"Nova Zelândia",
	"Omã",
	"Palau",
	"Palestina",
	"Panamá",
	"Papua Nova Guiné",
	"Paquistão",
	"Paraguai",
	"Peru",
	"Polônia",
	"Portugal",
	"Quênia",
	"Quirguistão",
	"Reino Unido da Grã-Bretanha e Irlanda do Norte",
	"República Centro-Africana",
	"República da Coreia",
	"República Democrática do Congo",
	"República Democrática Popular do Laos",
	"República Dominicana",
	"República Popular Democrática da Coreia",
	"República Tcheca",
	"Romênia",
	"Ruanda",
	"Samoa",
	"San Marino",
	"Santa Lúcia",
	"São Cristóvão e Nevis",
	"São Tomé e Príncipe",
	"São Vicente e Granadinas",
	"Seichelles",
	"Senegal",
	"Serra Leoa",
	"Sérvia",
	"Singapura",
	"Síria",
	"Somália",
	"Sri Lanka",
	"Sudão",
	"Sudão do Sul",
	"Suécia",
	"Suíça",
	"Suriname",
	"Tadjiquistão",
	"Tailândia",
	"Tanzânia, República Unida da",
	"Timor-Leste",
	"Togo",
	"Tonga",
	"Trinidad e Tobago",
	"Tunísia",
	"Turcomenistão",
	"Turquia",
	"Tuvalu",
	"Ucrânia",
	"Uganda",
	"Uruguai",
	"Uzbequistão",
	"Vanuatu",
	"Venezuela (República Bolivariana da)",
	"Vietnã",
	"Zâmbia",
	"Zimbábue"
];